### ISSUE TITLE
using hostsfile could be enough

### ISSUE THREAD

**Issue by nyov** [advoid/advoid#1]
I think using a stub DNS server in this scenario may be overkill (but YMMV).
Here is a solution just using `/etc/hosts`:

https://gist.github.com/nyov/248ac09eac7f2849bbff

**Comment by shibumi** [comment]
Hello nyov,
You haven't understand the point of our project. We know your solution. The thing is that your solution is only for your Laptop. So when somebody else is in your network he will see ads.
With our solution you can install a DNS server on a raspi for example and set this raspi as DNS for your own wifi. So everybody in your wifi will have ad-free internet. Doesn't matter if they are windows/mac/linux users. And nobody needs to install something. We are just forwarding the DNS requests through our own DNS server and blocking all bad DNS requests for  ads via /etc/hosts on the DNS server.

**Comment by nyov** [comment]
AH, I see how I fumbled that. Need the DNS resolver for network-wide lookups of course.

Though you also assume wrong; the given script does actually run on a gateway and is enforced in the local network. That's because a transparent http proxy on that system is using the hostsfile before DNS. ...but, yeah, that's like running a local resolver doing the same. So nevermind.

**Comment by hanez** [comment]
nyov,

anyway, thank you for your contribution... :)

May I ask how you found the advoid project?

**Comment by nyov** [comment]
I must admit I can't quite retrace it now, but it was more of a drive-by while browsing through some github projects. Finding the strangest things ;)

**Comment by hanez** [comment]
Okay, thanks... Your script is nice and it is really cool to see people forcing the same idea... ;)
